name: CICD Mobile Geni

# event trigger the cicd
on:
  pull_request:
    types:
      - closed
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build-docker-image:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      #build the docker file
      - name: Code Checkout
        uses: actions/checkout@v2

      # setup QEMU Emulator
      - name: setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: geniwhitelabel/pwa:${{ steps.branch-name.outputs.current_branch }}

  deploy-to-production:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    needs: build-docker-image

    steps:
      - name: get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1

      - name: set var name
        run: |
          echo "branch=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV

      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_EDIMU_SERVER }}
          username: ${{ secrets.SSH_USERNAME_EDIMU_SERVER }}
          password: ${{ secrets.SSH_PASSWORD_EDIMU_SERVER }}
          port: 22
          script: |
            cd /var/docker/mobile_project/${{ env.branch }}
            docker pull geniwhitelabel/pwa:${{ env.branch }}
            docker-compose down
            docker-compose up -d
